### ISSUE TITLE
Error - link point to wrong destination

### ISSUE THREAD

**Issue by Domarys** [shellhub-io/website#24]
When acessing with mobile, the Documentation link send to home instead of to the documentation.
@leonardojoao

**Comment by leonardojoao** [comment]
@Domarys can you send the image indicating where it is?

**Comment by Domarys** [comment]
![link](https://user-images.githubusercontent.com/13737233/115905350-5e2e0780-a43c-11eb-9e73-4bb2e76227e5.png)
clicking in Documentation, send the user to new window with Home, don't to Documentation.
![link2](https://user-images.githubusercontent.com/13737233/115905354-5ec69e00-a43c-11eb-9f2c-d9001a823f3d.png)
